package Clases;
// default package
// Generated 8 ene 2022 23:38:39 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos implements java.io.Serializable {

	private int idEquipo;
	private String nombre;
	private String ciudad;
	private String division;
	private Set jugadoreses = new HashSet(0);

	public Equipos() {
	}

	public Equipos(int idEquipo, String nombre) {
		this.idEquipo = idEquipo;
		this.nombre = nombre;
	}

	public Equipos(int idEquipo, String nombre, String ciudad, String division, Set jugadoreses) {
		this.idEquipo = idEquipo;
		this.nombre = nombre;
		this.ciudad = ciudad;
		this.division = division;
		this.jugadoreses = jugadoreses;
	}

	public int getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(int idEquipo) {
		this.idEquipo = idEquipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	public Set getJugadoreses() {
		return this.jugadoreses;
	}

	public void setJugadoreses(Set jugadoreses) {
		this.jugadoreses = jugadoreses;
	}

}
