package Clases;
// default package
// Generated 9 ene 2022 12:31:40 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * Jugadores generated by hbm2java
 */
public class Jugadores implements java.io.Serializable {

	private int idJugador;
	private Equipos equipos;
	private String nombre;
	private String posicion;
	private Float peso;
	private Date fechaAlt;

	public Jugadores() {
	}

	public Jugadores(int idJugador) {
		this.idJugador = idJugador;
	}

	public Jugadores(int idJugador, Equipos equipos, String nombre, String posicion, Float peso, Date fechaAlt) {
		this.idJugador = idJugador;
		this.equipos = equipos;
		this.nombre = nombre;
		this.posicion = posicion;
		this.peso = peso;
		this.fechaAlt = fechaAlt;
	}

	public int getIdJugador() {
		return this.idJugador;
	}

	public void setIdJugador(int idJugador) {
		this.idJugador = idJugador;
	}

	public Equipos getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Equipos equipos) {
		this.equipos = equipos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPosicion() {
		return this.posicion;
	}

	public void setPosicion(String posicion) {
		this.posicion = posicion;
	}

	public Float getPeso() {
		return this.peso;
	}

	public void setPeso(Float peso) {
		this.peso = peso;
	}

	public Date getFechaAlt() {
		return this.fechaAlt;
	}

	public void setFechaAlt(Date fechaAlt) {
		this.fechaAlt = fechaAlt;
	}

}
